name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Ensure no old datagenned files are present
        run: test ! -d ./src/main/resources_generated

      - name: Run Datagen
        run: ./gradlew runDatagen --stacktrace

      - name: Validate Datagen results
        run: test -d ./src/main/resources_generated/.cache

      - name: Build the mod
        run: ./gradlew build --stacktrace -x runDatagen

      - name: Publish 1.17 version
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: 495731
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          files-primary: build/libs/!(*-@(dev|sources)).jar

          name: 3.1.0 for MC 1.19 to 1.19.2
          version: 3.1.0+1.19
          version-type: release

          loaders: |
            fabric

          game-versions: |
            1.19
            1.19.1
            1.19.2

          dependencies: |
            fabric-api       | depends
